apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadboad-rest
  name: loadboard-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadboard-rest
  strategy: {}
  template:
    metadata:
      labels:
        app: loadboard-rest
    spec:
      containers:
      - image: $IMAGE
        name: loadboard-rest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadboard-rest
  name: loadboard-rest
spec:
  selector:
    app: loadboard-rest
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: loadboard-poc-rest-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /loadboard-rest
            backend:
              serviceName: loadboard-rest
              servicePort: 8080
