apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: maven
      image: maven:3-jdk-8-alpine
      command: ['cat']
      tty: true
      imagePullPolicy: Always
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2
        - name: workspace
          mountPath: /var/workspace
    - name: dind
      image: docker:19.03-dind
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
        - name: workspace
          mountPath: /var/workspace
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pv-claim
    - name: workspace
      emptyDir: {}

